name: Clojure CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install Clojure
      run: |
        curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        chmod +x linux-install.sh
        sudo ./linux-install.sh      

    - name: Run build
      run: clojure -T:build ci
